---
- hosts: localhost
  #sudo: yes
  tasks:
  - name: install apache2
    apt: name=apache2 state=latest

      #  - name: ensure apache is running (and enable it at boot)
      # service: name=apache2 state=started enabled=yes
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
