---
- name: Launching an EC2 Instance
  hosts: localhost
  gather_facts: false

  vars:
    keypair: ec2-server-demo
    instance_type: t2.micro
    security_group: default
    image: ami-0d13e2317a7e75c95
    region: us-west-2
    subnet_id: subnet-0d838522e17b8e59f

  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        name: ansible-demo-server
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        security_groups:
          - "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        network:
          assign_public_ip: true
        wait: true
        count: 1

      register: ec2

    - name: Display EC2 details
      debug:
        var: ec2
