---
- hosts: localhost
  tasks:
  - name: installing multiple packages
    become: yes
    apt: name={{item}} state=present
    with_items:
      - docker.io
      - nginx
      - tomcat9
      - mysql-server
